### ISSUE TITLE
Setup release CI workflow

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/docker#18]
This issue seeks to setup CI pipeline to build, push and publish official release images.

### Dependencies
- [x] [Minor changes after repository move](https://github.com/redwoodjs/docker/issues/12)
- [ ] [Define image name and tags](https://github.com/redwoodjs/docker/issues/15)
- [ ] [Define official Docker image(s)](https://github.com/redwoodjs/docker/issues/16)

### Implementation
- [ ] Define a baseline workflow template from [development findings](https://github.com/redwoodjs/docker/issues/17)
  - [ ] Prerequisites (environment variables, image tag)
  - [ ] Build image
  - [ ] Test image
  - [ ] Push image to Container Registry
  - [ ] Publish image
- [ ] Test
- [ ] Build on releases 🚀

**Comment by jeliasson** [comment]
Closing issue in preparation for archiving.
